### ISSUE TITLE
It looks like there is something wrong before it works normally

### ISSUE THREAD

**Issue by JK-Love** [jurelou/epagneul#10]
hi
Thank you very much for providing such a tool. I will deploy it in my virtual machine as soon as I see it
In the figure below, you can see that everything is going well, but when I visit the website, I am prompted 404

![image](https://user-images.githubusercontent.com/63699609/190970071-3ae551b2-2479-4f13-b151-8b291c6eb102.png)

I think it may be the problem of python I hope you can provide detailed deployment steps to correct my mistakes
![image](https://user-images.githubusercontent.com/63699609/190972463-01bb8daf-0467-425f-8b1e-b8ddcd47b61c.png)

**Comment by jurelou** [comment]
Hello, sorry for the late answer.

Can u tell me which version of docker (`docker -v`) and docker-compose (`docker-compose --version`) are u running ?
Are you using the latest version of epagneul ? (`main` branch)

also, I see that neo4j (the database behind epagneul) is not running properly. Can you give me the output of   `docker logs -f neo4j`

**Comment by JK-Love** [comment]
![image](https://user-images.githubusercontent.com/63699609/192665732-7c8b35c6-4dd4-4cc4-a670-8610f2169e86.png)
yes i use latest version main branch

**Comment by jurelou** [comment]
I see that you are using a pretty old docker version (1.13 is from ~2017).
Can you try to update docker to at least ~20.0 ? 

I guess you are using centos, here is an install guide: https://docs.docker.com/engine/install/centos/

**Comment by JK-Love** [comment]
After I update the Docker version, it runs successfully, but I can't access anything with my browser
![image](https://user-images.githubusercontent.com/63699609/193242523-2b073782-6623-43e3-a80d-78f8f8f65265.png)

**Comment by jurelou** [comment]
pretty strange that curl is not responding anything (i guess it should at least respond with "connection refused".

Can you give me the output of `curl -v localhost:8080`
