### ISSUE TITLE
unsupported operand type(s) for -: 'NoneType'

### ISSUE THREAD

**Issue by martinr666** [jurelou/epagneul#9]
The import into a folder fails for some of the evtx logs due to an error relating to an unsupported operand type 'NoneType'

**Comment by jurelou** [comment]
Hello,

can you give me an example evtx that causes this problem?
FYI, epagneul only supports `security` and `sysmon` channels.

**Comment by martinr666** [comment]
That explains the issue it was with the application.evtx so happy to close the issue.
